// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Entities;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628113809_InitialMSSQLSchema")]
    partial class InitialMSSQLSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Entities.JobEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("JobId");

                    b.Property<string>("ComputeType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ComputeType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<double>("CreditCost")
                        .HasColumnType("float")
                        .HasColumnName("CreditCost");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int")
                        .HasColumnName("ExecutionDuration");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("JobName");

                    b.Property<string>("OutputFileReference")
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("OutputFileReference");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ProjectId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status");

                    b.HasKey("JobId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Jobs_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Jobs_Status");

                    b.ToTable("Jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
